[character]
success_symbol = "[\uf120  ](bold bg:white fg:black)[\ue0b0 ](fg:white) "
error_symbol = "[\uf188  ](bold bg:white fg:red)[\ue0b0 ](fg:white)"


[directory]
truncation_length = 6
truncation_symbol = ".../"
disabled = false
home_symbol = "~"
read_only = "\uf023 "
read_only_style = "red"
format = "[ $path [$read_only](fg:red bg:#2587be)](bg:#2587be)[\ue0b0 ](fg:#2587be)"

[username]
style_user = "black"
style_root = "red"
format = "[ \uf2bd [$user ](bold bg:white fg:$style)](bold bg:white fg:$style)[\ue0b0](bg:#2587be fg:white)"
disabled = false
show_always = true

[time]
disabled = false
time_format = "%I:%M%p"
format = "[ $time ](bold bg:white fg:black)"
time_range = "00:00:00-00:00:00"

[rust]
symbol = "\ue07a "
